import Navbar from "../src/components/nav-menu";
import Head from "next/head";
import LogoIcon from "@/src/assets/2.png";
import Leftside from "../src/components/leftsidenav";
import RightSide from "../src/components/rightSide";
import Middle from "../src/components/Middle";
import About from "../src/components/About";
import { motion } from "framer-motion";
import Experience from "@/src/components/Experience";
import Projects from "@/src/components/Projects";

const Home = () => {
  return (
    <>
      <Head>
        <title>My Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={LogoIcon.src} />
      </Head>
      <main className="w-full h-screen font-bodyFont bg-bodyColor text-textLight overflow-x-hidden overflow-y-scroll">
        <Navbar />
        <div className="w-full h-[88vh] xl:flex items-center gap-20 justify-between">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            className="hidden xl:inline-flex w-32 h-full fixed left-0 bottom-0"
          >
            <Leftside />
          </motion.div>
          <div className="h-[88vh] w-full mx-auto p-4">
            <Middle/>
            <About />
            <Experience/>
            <Projects/>
          </div>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            className="hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0"
          >
            <RightSide />
          </motion.div>
        </div>
      </main>
    </>
  );
};
export default Home;
