import Navbar from "../src/components/nav-menu";
import Head from "next/head";
import LogoIcon from "@/src/assets/2.png";
import Leftside from "../src/components/leftsidenav";
import RightSide from "../src/components/rightSide";
import Middle from "../src/components/Middle";
import About from "../src/components/About";
import { motion } from "framer-motion";
import Experience from "@/src/components/Experience";
import Projects from "@/src/components/Projects";
import Cards from "@/src/components/Cards";
import Contact from "../src/components/Contact";
import Footer from "@/src/components/footer";
import Tech from "@/src/components/tech";


const Home = () => {
  return (
    <>
      <Head>
        <title>My Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={LogoIcon.src} />
      </Head>
      <main className="w-full h-screen font-bodyFont bg-[#E1E5EA] text-textLight">
        <Navbar />
          <div className="h-[88vh] w-full mx-auto p-4">
            <Middle/>
            <About />
            <Tech/>
            {/* <Experience/> */}
            <Projects/>
            <Cards/>
            <Contact/>
            <Footer/>
          </div>         
      </main>
    </>
  );
};
export default Home;
